### ISSUE TITLE
Trouble expressing some RegEx with VerEx

### ISSUE THREAD

**Issue by milesfrain** [VerbalExpressions/PurescriptVerbalExpressions#10]
I'm having difficulty translating these regular expressions to verbal expressions:

1. Match an any-case letter followed by a lower-case letter:

RegEx: `^[A-Za-z][a-z]$`
VerEx:
```hs
startOfLine
withAnyCase -- Sets global `i` (ignore case) flag
lower
lower -- This is withAnyCase too
endOfLine
```
Wondering if a solution is to add a `letter` expression as `[A-Za-z]`.

2. Match anything but empty or whitespace:

RegEx: `[^\s]`
VerEx:
```hs
anythingBut whitespace  -- Does not compile because anythingBut expects a String
```

**Comment by sharkdp** [comment]
TBH, I haven't worked on this project in a long time. Neither did I work on any of my PureScript projects. This project would first have to be updated to a recent version of PS.

I think you are right that there is currently no mechanism to express something as simple as `[A-Za-z]` (or, for that matter, any kind of alternation). To be completely honest: this project was more of a demo. I wanted to demonstrate (to myself) that free monads would be a suitable tool to build a DSL for Verbal Expressions. I'm not completely sure if verbal expressions in general are such a great idea. I tend to use plain regexes myself :smile: 

That being said, if somebody wants to continue working on this project, I'm happy to add them as maintainers.

**Comment by milesfrain** [comment]
Thanks for clarifying.

I originally found this package via this endorsement https://github.com/purescript/purescript-strings/issues/48#issuecomment-170805634, although it's a bit dated.

Also, looks like there are no incompatibilities with latest PS. It just needs to be republished, but that's probably best done after the new registry is live.

I'll continue the investigation for how to eliminate `unsafePartial` with regexes.

**Comment by paluh** [comment]
Hi,

@sharkdp this is a really nice DSL experiment! Thanks for building it up.

I wonder what would you say for a proposition to drop global flags combinators like `withAnyCase` from the DSL itself (push this kind of setup "outside").

Regarding sets and ranges construction I wonder if it would be enough to introduce a separate combinator like `CharSet` node and turn plain Strings into something like `data Str = Safe String | Raw String` to mark which parts should be escaped during the final `fold` of a character set. What do you think Guys?

**Comment by milesfrain** [comment]
Is the right long-term strategy to have verbal-expression blocks generate regex strings, and if so, do we expect it possible to map to every possible valid regex string (and guarantee no generation of invalid regex strings)?

Or would it be better to treat this like a PS-only parser and avoid generating regex strings? This strategy may improve safety, although would likely be much slower than native JS regex.

**Comment by timjs** [comment]
> Is the right long-term strategy to have verbal-expression blocks generate regex strings, and if so, do we expect it possible to map to every possible valid regex string (and guarantee no generation of invalid regex strings)?
> 
> Or would it be better to treat this like a PS-only parser and avoid generating regex strings? This strategy may improve safety, although would likely be much slower than native JS regex.

I didn’t look into the code, but multiple “backends” would solve this, wouldn’t it?

**Comment by milesfrain** [comment]
Do you mean the inverse: That the PS-only parser would more easily enable multiple backends?

Or that targeting multiple backends would force a PS-only parser implementation? I think all current backends have native regex support though.
