### ISSUE TITLE
Add upper, lower

### ISSUE THREAD

**Issue by paf31** [VerbalExpressions/PurescriptVerbalExpressions#6]
It would be nice to match more common character classes. You have `digit` but not `upper` and `lower`.

**Comment by paf31** [comment]
Having looked into this more, it doesn't seem very simple to implement these in JS, for arbitrary unicode input, even using vanilla regexen.

**Comment by sharkdp** [comment]
Definitely a good point. What about just adding (non-unicode-aware) `[a-z]` and `[A-Z]`?

**Comment by paf31** [comment]
That could be useful. Maybe it's enough to document the fact that they are ascii only.
